### ISSUE TITLE
Parse errors should show the filename in concern too

### ISSUE THREAD

**Issue by auscompgeek** [wenkokke/talonfmt#18]
@nriley noticed when attempting to merge up his knausj fork that a parse error doesn't say what file broke.

**Comment by wenkokke** [comment]
Strange, it should do that, unless it’s not properly recording the filename 🤔

**Comment by wenkokke** [comment]
@auscompgeek Could you provide an example file where this happens?

**Comment by auscompgeek** [comment]
I think @nriley had a file with some indented comments when trying to resolve merge conflicts. Can't remember for sure though.

**Comment by nriley** [comment]
Here's another example. The name of the file where the parse error occurred (`date_time.talon`) is nowhere in the output. (I filed the parse error itself separately in #23).

```
talonfmt.................................................................Failed
- hook id: talonfmt
- exit code: 1
- files were modified by this hook

Fixed apps/onenote/onenote_mac.talon
Fixed core/help/user_subl.talon
Fixed apps/outlook/outlook_win.talon
Fixed apps/mail/mail.talon
Fixed apps/fastscripts/fastscripts.talon
Fixed apps/fluent_search/fluent_search.talon
Fixed apps/black_ink.talon
Traceback (most recent call last):
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 177, in cli
    format_file(file_or_dir)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 166, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 137, in format
    output = talonfmt(
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/__init__.py", line 118, in talonfmt
    ast.assert_equivalent(ast_for_formatted)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 194, in assert_equivalent
    field_type.assert_equivalent(field1, field2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 122, in assert_equivalent
    node1.assert_equivalent(node2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 126, in assert_equivalent
    assert isinstance(child1, Node)
AssertionError
Fixed apps/excel/excel.talon
Fixed core/modes/wake_and_sleep.talon
Fixed apps/onenote/onenote_win.talon
Parse error on line 29 between column 21 and 27:
time <number_small> o'clock [<user.ampm>]:
                     ^^^^^^^              
Fixed apps/outlook/outlook_mac.talon
Fixed apps/omnifocus/omnifocus.talon
Fixed apps/acorn.talon
Fixed apps/anylist.talon
Fixed apps/fantastical/fantastical_global.talon
Fixed apps/moom/moom.talon
Fixed apps/apple_terminal/talon_helpers_terminal.talon
Fixed apps/safari/safari.talon
Fixed apps/shortcuts/shortcuts.talon
Fixed apps/xcode/xcode.talon
Fixed apps/launchbar/launchbar.talon
Traceback (most recent call last):
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 177, in cli
    format_file(file_or_dir)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 166, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 137, in format
    output = talonfmt(
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/__init__.py", line 118, in talonfmt
    ast.assert_equivalent(ast_for_formatted)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 194, in assert_equivalent
    field_type.assert_equivalent(field1, field2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 122, in assert_equivalent
    node1.assert_equivalent(node2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 126, in assert_equivalent
    assert isinstance(child1, Node)
AssertionError
```

**Comment by fidgetingbits** [comment]
fwiw I just ran into this as well while running the community repo pre commit config across my own repo:

```
talonfmt.................................................................Failed
- hook id: talonfmt
- files were modified by this hook

Fixed apps/systemd/systemd.talon
Fixed apps/vim/plugins/vim_wiki.talon
Fixed apps/vim/vim_motion_mode.talon
Fixed lang/tags/data_null.talon
Fixed plugin/desktops/desktops.talon
Fixed apps/vim/vim_terminal_mode.talon
Parse error on line 163 between column 4 and 9:
put async: "async "
    ^^^^^^         
Fixed apps/evince/evince.talon
Fixed tags/snippets/snippets.talon
```

In this case there was an error in a file called `rust.talon` but wasn't indicated by the output.
