### ISSUE TITLE
Parse error on apostrophes in commands

### ISSUE THREAD

**Issue by nriley** [wenkokke/talonfmt#23]
Talon doesn't have a problem with this (found [here](https://github.com/nriley/knausj_talon/blob/2b0685e0bc3066316d53e5d6b6c838aa4ec70fb2/core/text/date_time.talon#L30)):

```talon
time <number_small> o'clock [<user.ampm>]:
```

but talonfmt does:

```
talonfmt.................................................................Failed
- hook id: talonfmt
- exit code: 1

Traceback (most recent call last):
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 177, in cli
    format_file(file_or_dir)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 166, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 137, in format
    output = talonfmt(
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/__init__.py", line 118, in talonfmt
    ast.assert_equivalent(ast_for_formatted)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 194, in assert_equivalent
    field_type.assert_equivalent(field1, field2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 122, in assert_equivalent
    node1.assert_equivalent(node2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 126, in assert_equivalent
    assert isinstance(child1, Node)
AssertionError
Parse error on line 29 between column 21 and 27:
time <number_small> o'clock [<user.ampm>]:
                     ^^^^^^^              
Traceback (most recent call last):
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 177, in cli
    format_file(file_or_dir)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 166, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/cli.py", line 137, in format
    output = talonfmt(
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/talonfmt/__init__.py", line 118, in talonfmt
    ast.assert_equivalent(ast_for_formatted)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 194, in assert_equivalent
    field_type.assert_equivalent(field1, field2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 122, in assert_equivalent
    node1.assert_equivalent(node2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 128, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 248, in assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 187, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repo7ep37dp1/py_env-python3.9/lib/python3.9/site-packages/tree_sitter_type_provider/node_types.py", line 126, in assert_equivalent
    assert isinstance(child1, Node)
AssertionError
```

**Comment by wenkokke** [comment]
Fixed in 0fc2e1e
