### ISSUE TITLE
Assertion on processing anchored, unparenthesized alternation

### ISSUE THREAD

**Issue by nriley** [wenkokke/talonfmt#93]
talonfmt fails due to an assertion when trying to process the following file:

```talon
^a|b: "test"
```

It works fine if I put `a|b` in parentheses.

I added some debugging in `tree_sitter_type_provider` to see what it's comparing since otherwise the assertion error is less than helpful (first line below).

```
expected match: TalonWord(text='a', type_name='word', start_position=Point(line=0, column=1), end_position=Point(line=0, column=2)) TalonWord(text='', type_name='word', start_position=Point(line=0, column=1), end_position=Point(line=0, column=1))
Traceback (most recent call last):
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/talonfmt/cli.py", line 181, in cli
    format_file(file_or_dir_path)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/talonfmt/cli.py", line 169, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/talonfmt/cli.py", line 140, in format
    output = talonfmt(
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/talonfmt/__init__.py", line 130, in talonfmt
    ast.assert_equivalent(ast_for_formatted)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 190, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 132, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 190, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 132, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 197, in assert_equivalent
    field_type.assert_equivalent(field1, field2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 126, in assert_equivalent
    node1.assert_equivalent(node2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 190, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 132, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 190, in assert_equivalent
    self.children.assert_equivalent(children1, children2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 132, in assert_equivalent
    child1.assert_equivalent(child2)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 253, in _assert_equivalent
    node_type.assert_equivalent(self, other)
  File "/Users/nicholas/.cache/pre-commit/repobnaqhkwk/py_env-python3/lib/python3.10/site-packages/tree_sitter_type_provider/node_types.py", line 203, in assert_equivalent
    assert node1.text == node2.text
AssertionError
```

**Comment by wenkokke** [comment]
It seems like the parser somehow produced an empty word.

**Comment by wenkokke** [comment]
The assertion that fails it's there to guarantee that formatting doesn't change the parse tree. However, it should be caught and rendered as a human readable error message.
